### ISSUE TITLE
Using `#` as a comment character.

### ISSUE THREAD

**Issue by ehiggs** [arcnmx/serde-ini#3]
I think in the strict interpretation of the `ini` format as used by Windows, `#` is not really a comment char (but commenting out a line like `#var1=a` means `#var1` is being set instead of `var1`). However, in the Python ConfigParser approximation, `#` are indeed comment characters. Would it be possible to have serde-ini treat `#` as a comment character?

**Comment by arcnmx** [comment]
Fixed by #4
